"""Generate blocks/: the LLM-friendly copy-paste product of the catalogue.

Two flavors per chart entry:
  blocks/design-system/CH-xx_DL-yy.md  colors resolved to hex, zero
                                       dependencies; paste into any
                                       design-system md or CLAUDE.md
  blocks/skill/CH-xx.md                role-based, themeable; paste into
                                       a skill next to a DL token block
  blocks/skill/DL-yy.md                the token block (palette + fonts)

Blocks are GENERATED, never hand-edited. Source of truth: specs/ and
tokens/. Regenerate:  python tools/build_blocks.py
The QA gate (validate.py) rebuilds them in memory and blocks on drift.
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def load(p):
    return json.loads(p.read_text(encoding="utf-8"))


def jblock(obj):
    return "```json\n" + json.dumps(obj, indent=2) + "\n```"


def bullets(items):
    return "\n".join(f"- {i}" for i in items)


def resolve(palette, chain):
    for role in chain:
        if role in palette:
            return palette[role], role
    raise KeyError(chain)


def ai_metadata(spec):
    m = spec["meta"]
    compact = {"code": spec["code"], "ovp_version": spec["ovp_version"],
               "intent": m["intent"], "form": m["form"],
               "data_required": m["data_required"], "family": m["relations"]["family"],
               "alternatives": m["relations"].get("alternatives", []),
               "see_instead": m["relations"].get("see_instead", [])}
    return "### AI metadata (for agent routing)\n" + jblock(compact)


def chart_common(spec):
    """Sections shared by both flavors of a chart block."""
    s = [ai_metadata(spec),
         f"\nUse when:\n{bullets(spec['use_when'])}",
         f"\nDo NOT use when:\n{bullets(spec['not_when'])}",
         "\n### Input data shape\n" + jblock(spec["data_shape"]),
         "\n### Exact layout (px on the canvas, follow literally)\n"
         + jblock({"canvas": spec["canvas"], "layout": spec["layout"],
                   **({"scale": spec["scale"]} if "scale" in spec else {})}),
         "\n### Rules\n" + bullets(spec["rules"]),
         "\n### Never do this\n" + bullets(spec["anti_patterns"]),
         "\n### QA before delivering\n"
         + "\n".join(f"- [ ] {q}" for q in spec["qa"])]
    return "\n".join(s)


def design_system_block(spec, tok):
    pal = tok["palette"]
    rows = ["| Element | Color |", "|---|---|",
            f"| background | `{pal['background']}` |"]
    for element, chain in spec["roles"].items():
        if chain and isinstance(chain[0], list):  # list of chains (e.g. segments)
            for idx, sub in enumerate(chain):
                hexv, _ = resolve(pal, sub)
                rows.append(f"| {element} {idx + 1} | `{hexv}` |")
        else:
            hexv, _ = resolve(pal, chain)
            rows.append(f"| {element} | `{hexv}` |")
    fonts = (f"- Title font: {tok['fonts']['display']['family']}, "
             f"weight {tok['fonts']['display']['weight']}\n"
             f"- All other text: {tok['fonts']['body']['family']}, "
             f"weight {tok['fonts']['body']['weight']} "
             f"(600 on highlighted items)")
    chrome = tok["chrome"]
    chrome_note = ("Draw the kicker bar and CAPS eyebrow defined in the layout, "
                   "and use title y_with_eyebrow." if chrome["eyebrow"]
                   else "No kicker, no eyebrow; title at the default y.")
    return f"""<!-- Generated by VizCatalogue. Do not hand-edit; regenerate from source. -->
<!-- Chart {spec['code']} {spec['name']} rendered in language {tok['code']} {tok['name']} -->

## {spec['name']} chart, {tok['name']} style

Render as SVG (or equivalent) on a {spec['canvas']['width']}x{spec['canvas']['height']} px canvas.
Every position, size, and color below is exact. No adjectives, no improvisation.

{chart_common(spec)}

### Colors (resolved, use these exact values)

{chr(10).join(rows)}

### Fonts

{fonts}

### Language chrome

{chrome_note}
"""


def skill_block(spec):
    def chain_str(ch):
        if ch and isinstance(ch[0], list):
            return "; ".join(" -> ".join(sub) for sub in ch)
        return " -> ".join(ch)
    roles = "\n".join(f"| {el} | {chain_str(ch)} |"
                      for el, ch in spec["roles"].items())
    return f"""<!-- Generated by VizCatalogue. Do not hand-edit; regenerate from source. -->
<!-- Chart {spec['code']} {spec['name']}, role-based (themeable) -->

## {spec['name']} chart ({spec['code']})

Render as SVG (or equivalent) on a {spec['canvas']['width']}x{spec['canvas']['height']} px canvas.
Colors are ROLES, not hex: resolve each role against the active design
language token block (a DL-xx block pasted next to this one). A role
chain like `benchmark -> muted` means use the first role the palette
defines.

{chart_common(spec)}

### Color roles

| Element | Role chain |
|---|---|
| background | background |
{roles}

### Fonts

Title uses the token block's `display` font; everything else uses
`body`. Weight 600 only on highlighted items.
"""


def cp_block(cp):
    roles = "\n".join(f"| {el} | {' -> '.join(ch)} |"
                      for el, ch in cp["roles"].items())
    return f"""<!-- Generated by VizCatalogue. Do not hand-edit; regenerate from source. -->
<!-- Component {cp['code']} {cp['name']}, role-based (themeable) -->

## Component: {cp['name']} ({cp['code']})

{cp['purpose']}

### Geometry (px, follow literally)

{jblock(cp['params'])}

### Color roles

| Element | Role chain |
|---|---|
{roles}

### Rules
{bullets(cp['rules'])}

### QA
{chr(10).join('- [ ] ' + q for q in cp['qa'])}
"""


def dl_block(tok):
    pal_rows = "\n".join(f"| {k} | `{v}` |" for k, v in tok["palette"].items())
    return f"""<!-- Generated by VizCatalogue. Do not hand-edit; regenerate from source. -->
<!-- Design language {tok['code']} {tok['name']} token block -->

## Design language: {tok['name']} ({tok['code']})

**{tok['philosophy']['motto']}** {tok['philosophy']['civilization']}: {tok['philosophy']['principle']}.

Status: {tok['status']}. Occasions: {', '.join(tok['occasions'])}.

### Design laws

{bullets(tok['philosophy']['laws'])}

### Constitution (deterministic communication contract)

| Dimension | Value |
|---|---|
{chr(10).join(f"| {k} | {v} |" for k, v in tok['constitution'].items())}

### Palette

| Role | Hex |
|---|---|
{pal_rows}

### Fonts

- display: {tok['fonts']['display']['family']}, weight {tok['fonts']['display']['weight']}
- body: {tok['fonts']['body']['family']}, weight {tok['fonts']['body']['weight']}

### Chrome

kicker: {str(tok['chrome']['kicker']).lower()}, eyebrow: {str(tok['chrome']['eyebrow']).lower()}

### Machine-readable tokens

{jblock(tok)}
"""


def chooser(specs):
    """CHOOSER.md: the decision entry point, generated from meta."""
    by_intent = {}
    for s in specs:
        for i in s["meta"]["intent"]:
            by_intent.setdefault(i, []).append(s)
    lines = ["<!-- Generated by tools/build_blocks.py from specs/. Do not hand-edit. -->",
             "",
             "# CHOOSER . which chart carries your message?",
             "",
             "Built entries only; the full planned map is TAXONOMY.md.",
             "Agents: match your message to an intent, check `see instead`",
             "before committing, then render `<code> in DL-xx`.",
             ""]
    for intent in sorted(by_intent):
        lines.append(f"## Intent: {intent}")
        lines.append("")
        for s in sorted(by_intent[intent], key=lambda x: x["code"]):
            m = s["meta"]
            lines.append(f"### {s['code']} {s['name']} ({m['form']})")
            lines.append(f"- Data: {m['data_required']}")
            lines.append(f"- Use when: {s['use_when'][0]}")
            lines.append(f"- Not when: {s['not_when'][0]}")
            for si in m["relations"].get("see_instead", []):
                lines.append(f"- See instead: {si['use']} when {si['when']}")
            alts = m["relations"].get("alternatives", [])
            if alts:
                lines.append(f"- Alternatives: {', '.join(alts)}")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def languages_index(toks):
    lines = ["<!-- Generated by tools/build_blocks.py from tokens/. Do not hand-edit. -->",
             "",
             "# Design languages index",
             "",
             "| Code | Name | Motto | Status | Background | Primary | Occasions |",
             "|---|---|---|---|---|---|---|"]
    for t in toks:
        lines.append(f"| {t['code']} | {t['name']} | {t['philosophy']['motto']} | "
                     f"{t['status']} | `{t['palette']['background']}` | `{t['palette']['primary']}` | "
                     f"{'; '.join(t['occasions'])} |")
    lines += ["",
              "Canonical tokens: `tokens/<code>.json`. Copy blocks: "
              "`blocks/skill/<code>.md`. Candidate languages promote to "
              "adopted after two real deliverables ship in them."]
    return "\n".join(lines) + "\n"


def decider(engine, toks):
    names = {t["code"]: t["name"] for t in toks}
    lines = ["<!-- Generated by tools/build_blocks.py from decision/engine.json. Do not hand-edit. -->",
             "", "# DECIDER . which design language?", "",
             "Resolve the LANGUAGE here first (audience, purpose, medium),",
             "then the chart via PATTERNS.md (what you found in the data) or",
             "CHOOSER.md (what your message is). Rules match top-down; every",
             "condition must hold; first full match wins.", "",
             "| # | If | Then | Why |", "|---|---|---|---|"]
    for i, r in enumerate(engine["rules"], 1):
        cond = ", ".join(f"{k} = {v}" for k, v in r["if"].items())
        lines.append(f"| {i} | {cond} | {r['then']} {names[r['then']]} | {r['why']} |")
    fb = engine["fallback"]
    lines += ["", f"No match: {fb['then']} {names[fb['then']]} ({fb['why']}).", "",
              "## Controlled vocabulary", ""]
    for k, vals in engine["vocabulary"].items():
        lines.append(f"- **{k}**: {', '.join(vals)}")
    lines += ["", "Chart specs MUST draw `meta.intent` values from the intent",
              "list above; the validator enforces it."]
    return "\n".join(lines) + "\n"


def patterns_doc(pats):
    lines = ["<!-- Generated by tools/build_blocks.py from patterns/. Do not hand-edit. -->",
             "", "# PATTERNS . what did you find in the data?", "",
             "The analytical layer above charts: recognize the pattern, read",
             "its meaning, then take the recommended chart codes into the DL",
             "chosen via DECIDER.md.", ""]
    for p in pats:
        lines += [f"## {p['code']} {p['name']}",
                  f"- Recognize: {p['recognition']}",
                  f"- It means: {p['meaning']}",
                  f"- Business reading: {p['business_reading']}",
                  f"- Show with: {', '.join(p['show_with'])}",
                  f"- Avoid: {'; '.join(p['avoid'])}", ""]
    return "\n".join(lines).rstrip() + "\n"


def questions_doc(bqs, nrs, specs):
    names = {s["code"]: s["name"] for s in specs}
    nr_names = {n["code"]: n["name"] for n in nrs}
    lines = ["<!-- Generated by tools/build_blocks.py from questions/ and narratives/. Do not hand-edit. -->",
             "", "# QUESTIONS . start from what the business is asking", "",
             "The top of the resolution chain: match the question, note the",
             "observations that confirm it, then take the pattern, the charts,",
             "and the narrative skeleton. Language selection stays with",
             "DECIDER.md.", ""]
    for b in bqs:
        lines += [f"## {b['code']} {b['question']}",
                  f"- Intent: {', '.join(b['intent'])}",
                  f"- You will observe: {'; '.join(b['observations'])}",
                  f"- Patterns: {', '.join(b['patterns']) if b['patterns'] else 'none'}",
                  "- Show with: " + ", ".join(f"{c} {names.get(c, '')}".strip()
                                              for c in b["charts"]),
                  f"- Tell it as: {b['narrative']} {nr_names[b['narrative']]}", ""]
    lines += ["## Narrative skeletons", ""]
    for n in nrs:
        secs = " -> ".join(s["role"] for s in n["sections"])
        lines += [f"### {n['code']} {n['name']} ({n['decision_style']})",
                  f"- Structure: {secs}", ""]
        for s in n["sections"]:
            lines.append(f"- **{s['role']}**: {s['guidance']}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def registry(specs, toks, pats, comps, recs, bqs=(), nrs=()):
    """REGISTRY.json: the machine index of every object (PROTOCOL 6.3)."""
    objs = []
    for f in sorted((ROOT / "catalogue" / "foundations").glob("FN-*.md")):
        first = f.read_text(encoding="utf-8").split("\n")[0].lstrip("# ")
        code, _, name = first.partition(" . ")
        objs.append({"id": code.strip(), "name": name.strip() or code,
                     "type": "foundation", "status": "stable",
                     "source": f"catalogue/foundations/{f.name}"})
    for f in sorted((ROOT / "catalogue" / "mechanisms").glob("MX-*.md")):
        first = f.read_text(encoding="utf-8").split("\n")[0].lstrip("# ")
        code, _, name = first.partition(" . ")
        objs.append({"id": code.strip(), "name": name.strip() or code,
                     "type": "mechanism", "status": "candidate",
                     "source": f"catalogue/mechanisms/{f.name}"})
    for t in toks:
        objs.append({"id": t["code"], "name": t["name"],
                     "type": "design-language",
                     "ovp_version": t.get("ovp_version", "0.1"),
                     "status": t["status"],
                     "occasions": t["occasions"],
                     "source": f"tokens/{t['code']}.json"})
    for p in pats:
        objs.append({"id": p["code"], "name": p["name"], "type": "pattern",
                     "status": "candidate", "relations": {"show_with": p["show_with"]},
                     "source": f"patterns/{p['code']}.json"})
    # knowledge-graph reverse edges: charts know what recommends and uses them
    answers = {}
    for b in bqs:
        for c in b["charts"]:
            answers.setdefault(c, []).append(b["code"])
    rec_by = {}
    for pt in pats:
        for c in pt["show_with"]:
            rec_by.setdefault(c, []).append(pt["code"])
    used_in = {}
    for rc in recs:
        for el in rc["elements"]:
            if el["type"] == "chart":
                used_in.setdefault(el["ref"], []).append(rc["code"])
    for s in specs:
        rel = {k: v for k, v in s["meta"]["relations"].items() if k != "family"}
        code = s["code"]
        rel["answers"] = sorted(answers.get(code, []))
        rel["recommended_by"] = sorted(rec_by.get(code, []))
        rel["used_in"] = sorted(used_in.get(code, []))
        objs.append({"id": code, "name": s["name"], "type": "chart",
                     "family": s["meta"]["relations"]["family"],
                     "ovp_version": s["ovp_version"], "status": "candidate",
                     "intent": s["meta"]["intent"],
                     "relations": rel,
                     "source": f"specs/{code}.json"})
    for cp in comps:
        objs.append({"id": cp["code"], "name": cp["name"], "type": "component",
                     "ovp_version": cp.get("ovp_version", "0.1"),
                     "status": "candidate",
                     "source": f"components/{cp['code']}.json"})
    for b in bqs:
        objs.append({"id": b["code"], "name": b["question"], "type": "question",
                     "ovp_version": b["ovp_version"], "status": "experimental",
                     "intent": b["intent"],
                     "relations": {"patterns": b["patterns"],
                                   "charts": b["charts"],
                                   "narrative": b["narrative"]},
                     "source": f"questions/{b['code']}.json"})
    for n in nrs:
        objs.append({"id": n["code"], "name": n["name"], "type": "narrative",
                     "ovp_version": n["ovp_version"], "status": "experimental",
                     "relations": {"decision_style": n["decision_style"]},
                     "source": f"narratives/{n['code']}.json"})
    for rc in recs:
        objs.append({"id": rc["code"], "name": rc["name"], "type": "recipe",
                     "ovp_version": rc.get("ovp_version", "0.1"),
                     "status": "candidate",
                     "relations": {"dl": rc["dl"],
                                   "charts": sorted({e["ref"] for e in rc["elements"]
                                                     if e["type"] == "chart"})},
                     "source": f"recipes/{rc['code']}.json"})
    objs.sort(key=lambda o: o["id"])
    doc = {"registry": "Open Visualization Protocol object index",
           "generated_by": "tools/build_blocks.py, do not hand-edit",
           "lifecycle_mapping": "PROTOCOL.md section 6.1",
           "objects": objs}
    return json.dumps(doc, indent=2) + "\n"


def build_all():
    """Return {relative_path: content} for every block."""
    out = {}
    specs = [load(p) for p in sorted((ROOT / "specs").glob("CH-*.json"))]
    toks = [load(p) for p in sorted((ROOT / "tokens").glob("DL-*.json"))]
    out["CHOOSER.md"] = chooser(specs)
    out["catalogue/languages/INDEX.md"] = languages_index(toks)
    engine = load(ROOT / "decision" / "engine.json")
    out["DECIDER.md"] = decider(engine, toks)
    pats = [load(p) for p in sorted((ROOT / "patterns").glob("PT-*.json"))]
    out["PATTERNS.md"] = patterns_doc(pats)
    comps = [load(p) for p in sorted((ROOT / "components").glob("CP-*.json"))]
    recs = [load(p) for p in sorted((ROOT / "recipes").glob("RC-*.json"))]
    bqs = [load(p) for p in sorted((ROOT / "questions").glob("BQ-*.json"))]
    nrs = [load(p) for p in sorted((ROOT / "narratives").glob("NR-*.json"))]
    out["QUESTIONS.md"] = questions_doc(bqs, nrs, specs)
    out["REGISTRY.json"] = registry(specs, toks, pats, comps, recs, bqs, nrs)
    for spec in specs:
        out[f"blocks/skill/{spec['code']}.md"] = skill_block(spec)
        for tok in toks:
            out[f"blocks/design-system/{spec['code']}_{tok['code']}.md"] = \
                design_system_block(spec, tok)
    for tok in toks:
        out[f"blocks/skill/{tok['code']}.md"] = dl_block(tok)
    for cp in comps:
        out[f"blocks/skill/{cp['code']}.md"] = cp_block(cp)
    return out


def main():
    for rel, content in build_all().items():
        p = ROOT / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(content, encoding="utf-8", newline="\n")
        print(f"wrote {rel}")


if __name__ == "__main__":
    main()
