"""Generate preview.html: every golden render side by side, for review.

Scans golden/CH-*/ for SVGs, inlines them, adds the entry's QA list and
data so comments can point at something precise. Regenerate any time:

    python tools/preview.py
"""

import html
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
import build_blocks as B  # noqa: E402

CSS = """
:root { --ink:#222; --body:#555; --line:#E2E8E8; --accent:#008080; --bg:#F7F9F9; }
* { margin:0; padding:0; box-sizing:border-box; }
body { font-family:'Segoe UI',Arial,sans-serif; color:var(--ink); background:var(--bg);
       padding:40px 48px 80px; }
h1 { font-size:22px; margin-bottom:4px; }
.sub { color:var(--body); font-size:13px; margin-bottom:32px; }
section { background:#fff; border:1px solid var(--line); border-radius:6px;
          padding:24px; margin-bottom:32px; }
h2 { font-size:16px; margin-bottom:2px; }
h2 span { color:var(--accent); }
.meta { color:var(--body); font-size:12px; margin-bottom:16px; }
.renders { display:flex; gap:24px; flex-wrap:wrap; }
figure { flex:1 1 420px; min-width:380px; }
figcaption { font-size:12px; font-weight:600; color:var(--body);
             letter-spacing:1px; margin-bottom:8px; }
figure svg { width:100%; height:auto; border:1px solid var(--line); }
details { margin-top:16px; font-size:12.5px; color:var(--body); }
summary { cursor:pointer; font-weight:600; color:var(--ink); }
ul { margin:8px 0 0 18px; }
li { margin-bottom:3px; }
pre { background:var(--bg); border:1px solid var(--line); padding:10px;
      font-size:11.5px; overflow-x:auto; margin-top:8px; }
.howto { background:#fff; border:1px solid var(--line); border-left:3px solid var(--accent);
         border-radius:6px; padding:16px 20px; margin-bottom:32px; font-size:13px;
         color:var(--body); }
.howto b { color:var(--ink); }
.copybar { display:flex; gap:8px; flex-wrap:wrap; margin-top:16px; }
.copybar button { font:600 12px 'Segoe UI',Arial,sans-serif; color:#fff;
  background:var(--accent); border:none; border-radius:4px; padding:7px 14px;
  cursor:pointer; }
.copybar button.alt { background:#fff; color:var(--accent);
  border:1px solid var(--accent); }
.copybar button.copied { background:#339966; border-color:#339966; color:#fff; }
"""

JS = """
function copyBlock(btn, id) {
  var t = document.getElementById(id).textContent;
  navigator.clipboard.writeText(t).then(function() {
    var old = btn.textContent;
    btn.classList.add('copied'); btn.textContent = 'Copied';
    setTimeout(function(){ btn.classList.remove('copied'); btn.textContent = old; }, 1500);
  }, function() {
    var r = document.createRange();
    r.selectNodeContents(document.getElementById(id));
    var s = window.getSelection(); s.removeAllRanges(); s.addRange(r);
    alert('Clipboard blocked: block selected, press Ctrl+C.');
  });
}
"""


def main():
    blocks = B.build_all()
    parts = ["<!DOCTYPE html><html><head><meta charset='utf-8'>",
             "<title>VizCatalogue review</title>",
             f"<style>{CSS}</style><script>{JS}</script></head><body>",
             "<h1>VizCatalogue . golden renders review</h1>",
             "<p class='sub'>Generated by tools/preview.py from golden/. "
             "Same data per chart, one column per design language.</p>",
             "<div class='howto'><b>How to comment:</b> reference the code and the "
             "language, e.g. \"CH-01 in DL-03: value labels too small\" or "
             "\"DL-02: muted teal too pale\". Batch everything into one message; "
             "each correction is filed into the spec or token file and the gate re-runs.</div>"]

    parts.append("<h2 style='font-size:16px;margin:8px 0 12px'>Recipes: fully determined pages</h2>")
    for rp in sorted((ROOT / "recipes").glob("RC-*.json")):
        rc = json.loads(rp.read_text(encoding="utf-8"))
        svgp = ROOT / "golden" / rc["code"] / f"{rc['code']}.svg"
        parts.append(f"<section><h2><span>{rc['code']}</span> . {rc['name']} "
                     f"<small style='color:#555;font-weight:400'>({rc['dl']})</small></h2>")
        parts.append(f"<figure style='max-width:980px'>{svgp.read_text(encoding='utf-8')}</figure></section>")

    parts.append("<h2 style='font-size:16px;margin:24px 0 12px'>Components</h2>")
    for cpp in sorted((ROOT / "components").glob("CP-*.json")):
        cp = json.loads(cpp.read_text(encoding="utf-8"))
        parts.append(f"<section><h2><span>{cp['code']}</span> . {cp['name']}</h2>"
                     f"<p class='meta'>{cp['purpose']}</p><div class='renders'>")
        for dl in ("DL-02", "DL-03", "DL-08"):
            svgp = ROOT / "golden" / cp["code"] / f"{cp['code']}_{dl}.svg"
            parts.append(f"<figure style='flex:0 1 300px;min-width:240px'>"
                         f"<figcaption>{dl}</figcaption>{svgp.read_text(encoding='utf-8')}</figure>")
        parts.append("</div></section>")

    parts.append("<h2 style='font-size:16px;margin:24px 0 12px'>Charts x languages</h2>")
    for d in sorted((ROOT / "golden").iterdir()):
        if not d.is_dir() or not d.name.startswith("CH-"):
            continue
        spec = json.loads((ROOT / "specs" / f"{d.name}.json").read_text(encoding="utf-8"))
        data = json.loads((d / "data.json").read_text(encoding="utf-8"))
        parts.append(f"<section><h2><span>{spec['code']}</span> . {spec['name']}</h2>")
        parts.append(f"<p class='meta'>{' / '.join(spec['use_when'])}</p>")
        parts.append("<div class='renders'>")
        for svg_path in sorted(d.glob("CH-*_DL-*.svg")):
            dl = svg_path.stem.split("_")[1]
            tok = json.loads((ROOT / "tokens" / f"{dl}.json").read_text(encoding="utf-8"))
            svg = svg_path.read_text(encoding="utf-8")
            parts.append(f"<figure><figcaption>{dl} {tok['name']}</figcaption>{svg}</figure>")
        parts.append("</div>")
        qa = "".join(f"<li>{q}</li>" for q in spec["qa"])
        parts.append(f"<details><summary>QA checklist</summary><ul>{qa}</ul></details>")
        parts.append("<details><summary>Input data</summary><pre>"
                     + json.dumps(data, indent=2) + "</pre></details>")

        variants = ([(f"Copy for design system ({dl})",
                      f"blocks/design-system/{spec['code']}_{dl}.md")
                     for dl in sorted(t.stem for t in (ROOT / "tokens").glob("DL-*.json"))]
                    + [("Copy for skill (themeable)",
                        f"blocks/skill/{spec['code']}.md")])
        parts.append("<div class='copybar'>")
        for i, (label, rel) in enumerate(variants):
            bid = f"blk-{spec['code']}-{i}"
            cls = " class='alt'" if "skill" in rel else ""
            parts.append(f"<button{cls} onclick=\"copyBlock(this,'{bid}')\">{label}</button>")
        parts.append("</div>")
        for i, (label, rel) in enumerate(variants):
            bid = f"blk-{spec['code']}-{i}"
            parts.append(f"<pre id='{bid}' style='display:none'>{html.escape(blocks[rel])}</pre>")
        parts.append("</section>")

    parts.append("</body></html>")
    out = ROOT / "preview.html"
    out.write_text("\n".join(parts), encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
